modLoader="javafml"
loaderVersion="${mod_forge_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/corpse/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/corpse.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/corpse"
# logoFile="corpse.png"
# credits=""
authors="${mod_vendor}"
description='''
This mod brings a corpse into the game.
It will spawn upon your death containing all items that you had in your inventory.
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"